### ISSUE TITLE
"Before going live TODO"

### ISSUE THREAD

**Issue by remojansen** [gon250/ng2-orderBy-pipe#14]
I know that you guys are already working on things like testing but here are some things that I recommend you to do before you advertise the project:

# "Before going live TODO"

- [ ] **DEPENDENCIES STATUS** Let people know if all your development dependencies (not just runtime) are up to date with https://david-dm.org badge.
- [ ] **UPDATE DEPENDENCIES** Configure automatic update of dependencies with https://greenkeeper.io
- [ ] **BROWSER TESTING** Run the unit tests in browsers. I use Karma with appveyor.com because Travis CI doesn't  include IE.
- [ ] **GITHUB TEMPLATES** Generate a PR and Issue template using https://www.talater.com/open-source-templates/
- [ ]  **CONTRIBUTING** Add CONTRIBUTING.md file so people know how to contribute ([example](https://github.com/inversify/InversifyJS/blob/master/CONTRIBUTING.md))
- [ ]  **COVERAGE** Ensure that you have at least 75% test coverage or people will not trust your library. You can create a badge using codeclimate.com.
- [ ]  **WIKI** Add a wiki to your source code. It is better to have the wiki as part of your source code so people can send PRs jut like they do with the normal source code.
- [ ] **ROADMAP** Add a roadmap to the wiki. It helps contributors to know what kind of things they can contribute.
- [ ] **QA** It is very important to show to the users of your library that you care about quality. [enable required build pass and required code reviews for all PRs](https://github.com/blog/2051-protected-branches-and-required-status-checks).
